/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdi_practica1;
import javax.swing.BoxLayout;
import org.math.plot.Plot2DPanel;

/**
 *
 * @author gerar
 */
public class MostrarHistogramas extends javax.swing.JFrame {

    /**
     * Creates new form MostrarHistogramas
     * @param red
     */
    public MostrarHistogramas(Plot2DPanel red, Plot2DPanel blue, Plot2DPanel green) {
        initComponents();
        this.setLayout(new BoxLayout(getContentPane(),BoxLayout.Y_AXIS));
        this.add(red);
        this.add(green);
        this.add(blue);
        //this.setContentPane(red);
        //this.setContentPane(blue);
    }
    public MostrarHistogramas(Plot2DPanel grays) {
        initComponents();
        this.setLayout(new BoxLayout(getContentPane(),BoxLayout.Y_AXIS));
        this.add(grays);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
